spring.application.name=shift-api
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=fintech

# 2. The Hibernate Magic (This tells Spring to automatically create our tables!)
spring.jpa.hibernate.ddl-auto=update

# 3. Show SQL (Prints the SQL queries to the console so we can see what Spring is doing)
spring.jpa.show-sql=true


